"""
This module defines the 'individual' table.
The individual table stores all individuals that have a sample and all associated metadata 
is either stored directly in the table or in additional tables that reference its primary key.
"""
from typing import List
import uuid
from sqlalchemy import String, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.dialects.postgresql import UUID

from database.schema.base import Base  # Adjust if needed
from database.schema.biological_sex_info import biological_sex_enum

class Individual(Base):
    """
    Individual table according to EGA.
    - individual_object_id: unique auto generated by the system per individual that has a sample
    - subject_id: custom created by the study submitter (not unique)
    -------minimalPublicAttributes---------------
    Among all attributes describing an individual, some may contain identifiable metadata
    and thus must be private. Nevertheless, there are three/four required attributes (even if
    they are unknown): subject id, biological sex, phenotypicAbnormalities and/or diseases.
    These shall be displayed and queryable on our portal. In the case of a healthy individual
    (with no phenotypic abnormalities nor diseases), the 'phenotypicAbnormalities' and 
    'diseases' arrays will contain a reference to 'Unaffected' [NCIT:C94232]. Do take into
    account the 'excluded' property of each 'disease' or 'phenotypicAbnormality' in order
    to evaluate it correctly, since logic negation can be provided using that property.
    - biological_sex
    - ethnicity_term_id
    """
    __tablename__ = 'individual'
    individual_object_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4
    )

    subject_id: Mapped[str] = mapped_column(
    String(50),
    nullable=False
    )

    biological_sex: Mapped[str] = mapped_column(
        biological_sex_enum,
        ForeignKey("biological_sex_info.biological_sex", ondelete="CASCADE"),
        nullable=False
    )

    ethnicity_term_id: Mapped[str] = mapped_column(
        String(50),
        ForeignKey('ontology_term.term_id', ondelete='CASCADE')
    )

    # TODO in DNAvi backend: Add subject_id logic: logged in user with email anja@domain.com uploads
    # image1 subjectId = “yara”, in the database create a unique subjectId encoding,
    # and check did this user upload previously “yara” if yes, ask them to confirm that
    # this is the same person from last uploaded image, otherwise if not just create a new
    # unique subjectId encoding. If user uploads anonymously (no identifiable email to trace them)
    # then upload each “yara” with a completely unique subjectId)
