"""
This module defines the 'subject' table.
The subject table stores all subjects that have a sample and all associated metadata 
is either stored directly in the table or in additional tables that reference its primary key.
"""
from datetime import datetime
import uuid
from sqlalchemy import DateTime, String, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.dialects.postgresql import UUID

from database.schema.base import Base
from database.schema.biological_sex_info import biological_sex_enum

class Subject(Base):
    """
    subject table according to EGA.
    - subject_id: unique auto generated by the system per subject that has a sample
    - subject_name: custom created by the study submitter (not unique)
    -------minimalPublicAttributes---------------
    Among all attributes describing an subject, some may contain identifiable metadata
    and thus must be private. Nevertheless, there are three/four required attributes (even if
    they are unknown): subject id, biological sex, phenotypicAbnormaly and/or disease.
    These shall be displayed and queryable on our portal. In the case of a healthy subject
    (with no phenotypic abnormality nor disease), the 'phenotypicAbnormality' and 
    'disease' arrays will contain a reference to 'Unaffected' [NCIT:C94232]. Do take into
    account the 'excluded' property of each 'disease' or 'phenotypicAbnormality' in order
    to evaluate it correctly, since logic negation can be provided using that property.
    - biological_sex
    - ethnicity_term_id
    ---------organismDescriptor-------------
    EGA: This property describes the material entity 
    the sample consists in. That is, an individual living system, such as animal, plant, bacteria 
    or virus, that is capable of replicating or reproducing, growth and maintenance in
    the right environment. An organism may be unicellular or, like humans, made
    up of many billions of cells divided into specialized tissues and organs.
    This node is of special interest in case the provenance of the sample is not
    human (e.g. microbiota taken from a donor). Unless stated otherwise, given the
    nature of the EGA, it is expected to be of human provenance.
    - organism_term_id: Taxonomic classification of the organism (e.g. 'NCBITaxon:9606' and 
     'homo sapiens' for humans) curated by the NCBI Taxonomy (search for organisms here:
      https://www.ncbi.nlm.nih.gov/taxonomy; or use the OLS: 
      https://www.ebi.ac.uk/ols/ontologies/ncbitaxon).
      You can find further details at 'https://www.uniprot.org/help/taxonomic_identifier'.
      This is appropriate for individual organisms and some environmental samples.
    - created_at : DateTime
      Timestamp when the record was inserted.
    """

    __tablename__ = 'subject'
    subject_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4
    )

    subject_name: Mapped[str] = mapped_column(
        String(50),
        nullable=True
    )

    biological_sex: Mapped[str] = mapped_column(
        biological_sex_enum,
        ForeignKey("biological_sex_info.biological_sex", ondelete="CASCADE"),
        nullable=True
    )

    ethnicity_term_id: Mapped[str] = mapped_column(
        String(50),
        ForeignKey('ontology_term.term_id', ondelete='CASCADE'),
        nullable=True
    )
    
    # ---------organismDescriptor fields-------------
    # organismDescriptor.organismTaxon
    organism_term_id: Mapped[str] = mapped_column(
        String(50),
        ForeignKey('ontology_term.term_id', ondelete='CASCADE'),
        nullable=True
    )
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.now(),
        nullable=False
    )

    # TODO in DNAvi backend: Add subject_id logic: logged in user with email anja@domain.com uploads
    # image1 subjectId = “yara”, in the database create a unique subjectId encoding,
    # and check did this user upload previously “yara” if yes, ask them to confirm that
    # this is the same person from last uploaded image, otherwise if not just create a new
    # unique subjectId encoding. If user uploads anonymously (no identifiable email to trace them)
    # then upload each “yara” with a completely unique subjectId)
