"""
This module defines the 'subject' table.
The subject table stores all subjects that have a sample and all associated metadata 
is either stored directly in the table or in additional tables that reference its primary key.
"""
import uuid
from sqlalchemy import String, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.dialects.postgresql import UUID

from database.schema.base import Base
from database.schema.biological_sex_info import biological_sex_enum

class Subject(Base):
    """
    subject table according to EGA.
    - subject_id: unique auto generated by the system per subject that has a sample
    - subject_name: custom created by the study submitter (not unique)
    -------minimalPublicAttributes---------------
    Among all attributes describing an subject, some may contain identifiable metadata
    and thus must be private. Nevertheless, there are three/four required attributes (even if
    they are unknown): subject id, biological sex, phenotypicAbnormalities and/or diseases.
    These shall be displayed and queryable on our portal. In the case of a healthy subject
    (with no phenotypic abnormalities nor diseases), the 'phenotypicAbnormalities' and 
    'diseases' arrays will contain a reference to 'Unaffected' [NCIT:C94232]. Do take into
    account the 'excluded' property of each 'disease' or 'phenotypicAbnormality' in order
    to evaluate it correctly, since logic negation can be provided using that property.
    - biological_sex
    - ethnicity_term_id
    """

    __tablename__ = 'subject'
    subject_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4
    )

    subject_name: Mapped[str] = mapped_column(
    String(50),
    nullable=True
    )

    biological_sex: Mapped[str] = mapped_column(
        biological_sex_enum,
        ForeignKey("biological_sex_info.biological_sex", ondelete="CASCADE"),
        nullable=True
    )

    ethnicity_term_id: Mapped[str] = mapped_column(
        String(50),
        ForeignKey('ontology_term.term_id', ondelete='CASCADE'),
        nullable=True
    )

    # TODO in DNAvi backend: Add subject_id logic: logged in user with email anja@domain.com uploads
    # image1 subjectId = “yara”, in the database create a unique subjectId encoding,
    # and check did this user upload previously “yara” if yes, ask them to confirm that
    # this is the same person from last uploaded image, otherwise if not just create a new
    # unique subjectId encoding. If user uploads anonymously (no identifiable email to trace them)
    # then upload each “yara” with a completely unique subjectId)
